[package]
name = "modbus-sample"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modbus = "1.0"
serial = "0.4"
crc16 = "0.4.0"