[package]
name = "av-in-rust"
version = "0.1.0"
edition = "2018"
authors = ["QidongTan qidongtan@qq.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-sys-next = "4.4.0"
ffmpeg-next = "4.4.0"